name: "CI"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 --version
        sudo snap install charmcraft --classic
        sudo snap refresh lxd --channel latest/stable

    - name: Set up LXD
      run: |
        sudo lxd waitready
        sudo lxd init --auto
        sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket

    - name: Pack charm
      run: |
        charmcraft pack -v

    - name: Upload packed charm as artifact
      uses: actions/upload-artifact@v2
      with:
        name: charm
        path: '*.charm'
